import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Jeets blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <div className="text-center bg-slate-800  p-8 my-6 rounded-md ">
        <Link href="/">
          <h2 className="text-3xl text-white font-bold">Jeet's Blog</h2>
        </Link>
        <p className="text-slate-200 pt-2">
          🖖 Hello! Welcome to my brain dump.
        </p>
      </div>
    </header>
  );

  const footer = (
    <footer className="border-t text-sm border-slate-400 mt-6 py-6 text-center text-slate-400">
      <p>© 2023 Developed by Jeet 🤙</p>
    </footer>
  );

  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
